services:
  - name: restbase
    module: hyperswitch
    conf:
      port: 7231
      salt: secret
      default_page_size: 125
      user_agent: RESTBase
      ui_name: RESTBase
      ui_url: https://www.mediawiki.org/wiki/RESTBase
      ui_title: RESTBase docs
      spec:
        x-request-filters:
          - path: lib/security_response_header_filter.js
        x-sub-request-filters:
          - type: default
            name: http
            options:
            allow:
              - pattern: '${MEDIAWIKI_PROTOCOL}://${MEDIAWIKI_SITE_SERVER}/api.php'
                forward_headers: true
              - pattern: http://localhost:8142
                forward_headers: true
              - pattern: /^https?:\/\//
        paths:
          /{domain:${MEDIAWIKI_SITE_SERVER}}:
            x-modules:
              - path: projects/example.yaml
                options:
                  action:
                    apiUriTemplate: '${MEDIAWIKI_PROTOCOL}://${MEDIAWIKI_SITE_SERVER}/api.php'
                    baseUriTemplate: '${MEDIAWIKI_PROTOCOL}://${MEDIAWIKI_SITE_SERVER}/${MEDIAWIKI_SITE_SERVER}/v1'
                  parsoid:
                    host: http://restbase:8142
                  table:
                    backend: sqlite
                    dbname: db.sqlite3
                    pool_idle_timeout: 20000
                    retry_delay: 250
                    retry_limit: 10
                    show_sql: false
                  mobileapps:
                    host: http://appservice.wmflabs.org
                  purged_cache_control: s-maxage=0, max-age=86400
                  purged_cache_control_client_cache: s-maxage=0, max-age=300
  - name: parsoid
    entrypoint: apiServiceWorker
    conf:
      useSelser: true
      serverPort: 8142
      serverInterface: 0.0.0.0
      debug: false
      mwApis:
        - domain: ${MEDIAWIKI_SITE_SERVER}
          prefix: ${MEDIAWIKI_SITE_SERVER}
          uri: '${MEDIAWIKI_PROTOCOL}://${MEDIAWIKI_SITE_SERVER}/api.php'

info:
  name: restbase

logging:
  name: restbase
  level: info

num_workers: 1